config/routes.rb
Rails.application.routes.draw do
  root controller: :rooms, action: :index	
  resources :room_messages
  resources :rooms
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :room_messages, dependent: :destroy,
                         inverse_of: :room
    validates :name, presence:true, uniqueness:true
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json()
    super().merge(user_avatar_url: user.gravatar_url)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message),
                                       username: params.dig(:room_message, :username)
  
    RoomChannel.broadcast_to @room, @room_message
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/navigation_bar' %>
          <div class="my-3">
            <%= yield %>
          </div>
        </div>
      </div>
      <div style="background:#dcdcff;color:black;font-weight: bold;" class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5">
        <!-- Copyright -->
        <div>
          Copyright © 2024. All rights reserved.
        </div>
        <!-- Copyright -->
      </div>  
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<script>
$(function(){
    $("#btnBack").click(function(){
      window.location.href = "/";
    });
});
</script>
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <button  type="button" name="btnBack" id="btnBack" class="btn btn-info" style="">Back</button>
  <%= form.submit "Save", class: 'btn btn-info' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="input-group">
  <div class="input-group-prepend">
  <%= link_to new_room_path, class: 'btn btn-info' do %>
    Create a room
  <% end %>
  </div>
</div>

<% if @rooms.present? %>

<div id="plist" class="people-list" style="overflow: auto;height:500px">
  <ul class="list-unstyled chat-list mt-2 mb-0">
  
    <% @rooms.each do |room| %>
      
      <a href="/rooms/<%= room.id %>">
      <li class="clearfix">
        <img src="../discussion.png" alt="Room">
        <div class="about">
          <div class="name"> <%= room.name %></div>
        </div>
      </li>
      </a>   

    <% end %>
  
  </ul>
</div>

<% else %>
  <div id="plist" class="people-list" style="padding:10px;">
    rooms are empty
  </div>
<% end %>

app/views/rooms/_rooms_select.html.erb
<div class="input-group">
  <div class="input-group-prepend">
  <%= link_to new_room_path, class: 'btn btn-info' do %>
    Create Room
  <% end %>
  </div>
</div>

<% if @rooms.present? %>

<div id="plist" class="people-list" style="overflow: auto;height:545px">
  <ul class="list-unstyled chat-list mt-2 mb-0">
  
    <% @rooms.each do |room| %>
      
      <% if @room.id == room.id %>
      
      <a href="/rooms/<%= room.id %>">
      <li class="clearfix active">
        <img src="../discussion.png" alt="Room">
        <div class="about">
          <div class="name"> <%= room.name %></div>
        </div>
      </li>
      </a> 

      <% else %>
      
      <a href="/rooms/<%= room.id %>">
      <li class="clearfix">
        <img src="../discussion.png" alt="Room">
        <div class="about">
          <div class="name"> <%= room.name %></div>
        </div>
      </li>
      </a>   

      <% end %>
     
    <% end %>
  
  </ul>
</div>

<% else %>
  <div id="plist" class="people-list" style="padding:10px;">
    rooms are empty
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div style="background:#dcdcff;" class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the ChatApp!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Creating a room
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms_select' %>
  </div>

  <div class="col">
    <div class="toast-container top-10 start-70 translate-bottom-x p-3">
      <div class="toast text-bg-warning" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
          <div class="d-flex gap-4">
            <span class="text-primary"><i class="fa-solid fa-circle-info fa-lg"></i></span>
            <div class="d-flex flex-grow-1 align-items-center">
              <span class="fw-semibold">Please type your message ..</span>
              <button type="button" class="btn-close btn-close-sm btn-close-black ms-auto" data-bs-dismiss="toast"
                aria-label="Close"></button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div style="background:#efefef;padding:10px;font-weight:bold;border-radius: 8px;">
    <span class="navbar-text" style=""><%= @room.name %></span>
    </div>

    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">

    <div class="chat-history">
    <ul class="m-b-0">

      <% @room_messages.each do |room_message| %>

        <li class="clearfix">
          <div class="message-data">
          <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
          <span style="font-size:12px;font-weight:bold"><%= room_message.user.username %></span>
          <span style="font-size:11px">(<%= room_message.created_at %>)</span>
          </div>
          <div class="message my-message"><%= room_message.message %></div>
        </li>

      <% end %>

      </ul>
      </div> 

    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input', placeholder: 'Message'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input', id: 'btnSubmit' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
      <input type="hidden" name="room_message[username]" id="room_message_username" value="<%= current_user.username %>">
    <% end %>
  </div>
</div>
<div class="d-none" data-role="message-template">
  <div class="chat-history">
    <ul class="m-b-0">
      <li class="clearfix">
        <div class="message-data">
          <img src="" class="avatar" alt="" data-role="user-avatar">
          <span style="font-size:12px;font-weight:bold" data-role="message-username"></span>
          <span style="font-size:11px" data-role="message-date"></span>
        </div>
        <div class="message my-message" data-role="message-text"></div>
      </li>
    </ul>
  </div> 
</div>

app/views/shared/_navigation_bar.html.erb
<nav style="background:#dcdcff;" class="navbar navbar-expand-lg navbar-dark justify-content-between">
  <a style="padding:10px;color:black;font-weight: bold;" class="navbar-brand">ChatApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div style="padding:10px;color:black;font-weight: bold;">
        <img class="avatar" src="<%= current_user.gravatar_url %>">
        Hai, <%= current_user.username %>
        <span>(<%= link_to 'Logout', destroy_user_session_path, method: :delete %>)</span>
    </div>
  <% end %>
</nav>